#!/bin/bash

echo "Enter file"
read file

echo "Enter pattern"
read pattern

if [ -f "$file" ]; then
    grep -o "$pattern" "$file"
    if [ $? -eq 0 ]; then
        echo "Pattern found"
    else
        echo "Pattern not found"
    fi
else
    echo "File does not exist"
fi
