#!/bin/bash

echo "Enter file name to save current logins:"
read file

who > "$file"

echo "Enter user name to check login:"
read user

if [ ! -f "$file" ]; then
    echo "File '$file' not found."
    exit 1
fi

grep -w "$user" "$file" > /dev/null

if [ $? -eq 0 ]; then
    echo "User '$user' is currently logged in."
else
    echo "User '$user' is NOT logged in or username is incorrect."
fi
