#!/bin/bash

echo "Enter dcode"
read dcode
echo "Enter descriptor"
read des

if [[ $dcode =~ ^[0-9]+$ ]]; then
     if [[ $des =~ ^[a-zA-Z]+$ ]]; then
          echo "$dcode $des added successfully"
          echo "$dcode $des" >> desig.lst
     else
          echo "$des is not alphabetic"
     fi
else
     echo "$dcode is not a digit"
fi

# Show current file contents
cat desig.lst

