#!/bin/bash

while read line; do
    sal=$(echo "$line" | cut -d ' ' -f 5)
    name=$(echo "$line" | cut -d ' ' -f 2)

    da=0   # ❌ Fixed: no spaces around =
    
    if echo "$sal" | grep -E -q '^[0-9]+$'; then
        if [ $sal -gt 6000 ]; then
            da=$(( sal * 25 / 100 ))
        else
            da=$(( sal * 30 / 100 ))
        fi
    fi

    hra=$(( sal * 10 / 100 ))
    gs=$(( sal + da + hra ))   # ✅ Correct arithmetic

    echo "Employee name: $name"
    echo "Employee gross salary: $gs"
done < empn.lst
