#!/bin/bash

echo "Enter units consumed"
read units

bill=0
if [ $units -le 200 ]; then
    bill=$(echo "$units * 0.80" | bc)
elif [ $units -le 300 ]; then
    bill=$(echo "200 * 0.80 + ($units - 200) * 0.90" | bc)
else
    bill=$(echo "200 * 0.80 + 100 * 0.90 + ($units - 300) * 1.0" | bc)
fi

bill=$(echo "$bill + 100" | bc)

if [ "$(echo "$bill > 400" | bc)" -eq 1 ]; then
    sur=$(echo "$bill * 0.15" | bc)
    bill=$(echo "$bill + $sur" | bc)
    echo "Surcharge applied"
fi

echo "Total bill = $bill"

